geneci infer-network --expression-data /Users/mbrown/Desktop/Research/Mastersproject/GENECI/test.csv \
                     --technique GENIE3_ET \
                     --technique CMI2NI \
                     --technique GENIE3_RF \
                     --technique INFERELATOR \
                     --technique RSNET \
                     --technique LEAP \
                     --technique PCACMI \
                     --technique CLR \
                     --technique LOCPCACMI \
                     --technique GRNBOOST2 \
                     --output-dir ../GENECI/lots_of_techniques