FROM rocker/tidyverse:latest

LABEL image.author.name "Matthew Brown"
LABEL image.author.email "brownmc@student.unimelb.edu.au"

#RUN R -e "install.packages('igraph',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN Rscript -e "install.packages('nlnet', dependencies=TRUE, repos='http://cran.rstudio.com/')"

ENV PATH=$PATH:/usr/games/
ENV DOCKER_DEFAULT_PLATFORM=linux/amd64